name: Nextdoor Automation

on:
  schedule:
    - cron: '0 9,17 * * *' # Runs at 9 AM and 5 PM daily (UTC time)
  workflow_dispatch: # Allows manual runs from the Actions tab

jobs:
  run-puppeteer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Puppeteer
        run: npm install puppeteer
